### ISSUE TITLE
Servers are assigned same UUIDs and then disconnected

### ISSUE THREAD

**Issue by cheracc** [zml2008/netevents#6]
In src/main/java/com/zachsthings/netevents/packet/ServerIDPacket.java

```
+    public void handle(Forwarder session) throws IOException {
 +        for (Forwarder f : session.getPlugin().getForwarders()) {
 +            if (serverUid.equals(f.getRemoteServerUUID())) {
 +                session.disconnect("This server already connected!");
 +                return;
 +            }
 +        }
 +        session.setRemoteServerUUID(serverUid);
 +    }
```

appears to set the remote serverUUID to the same as the local server, and this check then later disconnects them for being "already connected".

I'm no developer, but I managed to comment out that "for" block and the result seems to work, though each server does appear to then have 2 connections.

**Comment by zml2008** [comment]
Should be fixed in the latest dev builds (That code is to prevent each server from having 2 connections. The serverUid variable is the uid of the remote server. I've made sure that this won't let netevents disconnect itself.) It is still possible for there to be multiple connection attempts because synchronization of two networked processes is really hard (especially when there's not really one master).
